"""SceneSmith package.

SceneSmith is a Story Continuity Engine for maintaining evidence-backed canon
state across long-form stories.
"""

import logging

from scenesmith.canon import (
    CanonConflict,
    CanonDatabase,
    CanonEngine,
    CanonEntity,
    CanonError,
    CanonFactVersion,
    CanonRelationship,
    CanonSnapshot,
    CanonUpdater,
    CanonUpdateSummary,
    DuplicateEntityError,
    EntityType,
    Evidence,
    MissingEvidenceError,
    StoryPosition,
    UnknownEntityError,
)
from scenesmith.characters import (
    CanonCharacterCard,
    CanonCharacterFact,
    CharacterCard,
    CharacterCardBuilder,
    CharacterEngine,
    CharacterEngineError,
    CharacterFact,
    NotACharacterError,
)
from scenesmith.export import ExportEngine
from scenesmith.extraction import (
    AIExtractionClient,
    EntityExtractionEngine,
    EvidenceBoundedAIExtractor,
    ExtractedEntity,
    ExtractedFact,
    ExtractedRelationship,
    ExtractedStateChange,
    ExtractionResult,
    SceneEvidenceAnchor,
    SceneExtractionInput,
    SceneExtractor,
    StaticAIExtractionClient,
)
from scenesmith.importing import (
    EpubText,
    EpubTextExtractor,
    EvidenceAnchor,
    ImportedSentence,
    ImportedSource,
    SourceParagraph,
    StoryImporter,
)
from scenesmith.presentation import (
    CharacterProfileView,
    PresentationEngine,
    PresentationSection,
    ProductionPackView,
    SceneSheetView,
    WorldSheetView,
)
from scenesmith.projects import (
    ContinuityRecord,
    ContinuityReport,
    ContinuitySceneReport,
    ProjectRunResult,
    SceneSmithProjectRunner,
)
from scenesmith.prompts import CanonPromptBuilder, ProductionPack, PromptBundle, PromptEngine
from scenesmith.scenes import (
    CanonSceneContext,
    SceneAnalysis,
    SceneAnalyzer,
    SceneContext,
    SceneContextBuilder,
    SceneEngine,
    SceneEnvironmentSnapshot,
)
from scenesmith.timeline import (
    DuplicateChapterError,
    DuplicateEventError,
    DuplicateSceneError,
    DuplicateStateChangeError,
    InvalidTimelinePositionError,
    OverlappingStateChangeError,
    TimelineChapter,
    TimelineEngine,
    TimelineError,
    TimelineEvent,
    TimelineScene,
    TimelineStateChange,
)
from scenesmith.world import WorldEntityFact, WorldEntityState, WorldState, WorldStateBuilder

logging.getLogger(__name__).addHandler(logging.NullHandler())

__all__ = [
    "CanonConflict",
    "CanonDatabase",
    "CanonEngine",
    "CanonEntity",
    "CanonError",
    "CanonFactVersion",
    "CanonRelationship",
    "CanonSnapshot",
    "CanonUpdateSummary",
    "CanonUpdater",
    "CanonCharacterCard",
    "CanonCharacterFact",
    "CharacterCard",
    "CharacterProfileView",
    "CharacterCardBuilder",
    "CharacterEngine",
    "CharacterEngineError",
    "CharacterFact",
    "ContinuityRecord",
    "ContinuityReport",
    "ContinuitySceneReport",
    "DuplicateEntityError",
    "DuplicateChapterError",
    "DuplicateEventError",
    "DuplicateSceneError",
    "DuplicateStateChangeError",
    "EntityType",
    "EntityExtractionEngine",
    "Evidence",
    "EvidenceAnchor",
    "EpubText",
    "EpubTextExtractor",
    "ExportEngine",
    "ExtractedEntity",
    "ExtractedRelationship",
    "ExtractionResult",
    "ImportedSentence",
    "ImportedSource",
    "InvalidTimelinePositionError",
    "MissingEvidenceError",
    "NotACharacterError",
    "OverlappingStateChangeError",
    "PromptBundle",
    "ProductionPack",
    "PresentationEngine",
    "PresentationSection",
    "ProductionPackView",
    "ProjectRunResult",
    "CanonPromptBuilder",
    "AIExtractionClient",
    "EvidenceBoundedAIExtractor",
    "ExtractedFact",
    "ExtractedStateChange",
    "PromptEngine",
    "SceneSmithProjectRunner",
    "SceneContext",
    "SceneSheetView",
    "SceneAnalysis",
    "SceneAnalyzer",
    "CanonSceneContext",
    "SceneContextBuilder",
    "SceneEngine",
    "SceneEvidenceAnchor",
    "SceneExtractionInput",
    "SceneExtractor",
    "StaticAIExtractionClient",
    "SceneEnvironmentSnapshot",
    "SourceParagraph",
    "StoryPosition",
    "StoryImporter",
    "TimelineChapter",
    "TimelineEngine",
    "TimelineError",
    "TimelineEvent",
    "TimelineScene",
    "TimelineStateChange",
    "UnknownEntityError",
    "WorldEntityFact",
    "WorldEntityState",
    "WorldSheetView",
    "WorldState",
    "WorldStateBuilder",
]
